sudo: required

services:
  - docker

before_install:
  - docker build -t romanwhales/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run romanwhales/react-test npm test -- --coverage

after_success:
  - docker build -t romanwhales/multi-client ./client
  - docker build -t romanwhales/multi-nginx ./nginx
  - docker build -t romanwhales/multi-server ./server
  - docker build -t romanwhales/multi-worker ./worker

  #Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push romanwhales/multi-client 
  - docker push romanwhales/multi-nginx
  - docker push romanwhales/multi-server
  - docker push romanwhales/multi-worker
  
